### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Kacawi** [tommyjee/articles#1]
Hi Tom!

I just looked over your article and it looks awesome! I have a couple of tips for you to make the article fit a little bit better with the DataCamp style:
- [x] Use "you" instead of "we" to actively draw the reader in
- [x] The first introductory sentences are awesome! If you'd like them to come up in bold on top of the tutorial just like on the Community page, though, you need to be careful not to exceed 150 chars!
- [x] You can add subtitles/subsections to the tutorial. This will make the structure of the tutorial more clear and will definitely help out readers! 
- [x] Additionally, feel free to add in **Note** or **Tip** if you'd like to recap or refresh some knowledge for the reader. 
- [x] Kudos for the great formatting of the tutorial!
- [x] I like the motivational shouts you added in this tutorial to keep readers motivated. Sometimes, you can add an extra white line in between the motivational shout and the rest of the text that comes after it to increase reader engagement (keep the reader longer on the page) and to let them take a short break from your tutorial!
- [x] We never mention sources of data as `(Source:Kaggle)`, but we do opt to link to relevant sources within the text. Eg. ```[nutritional data](link to kaggle)```

That's it! Great job with this tutorial, I love it!

**Comment by tommyjee** [comment]
Hey Karlijn! Thanks so much for the feedback. I will make another set of revisions later this week. Glad you liked what I have so far!

**Comment by tommyjee** [comment]
@Kacawi Just wondering, what's the process like for embedding DataCamp's consoles in the tutorial?

**Comment by Kacawi** [comment]
HI @tommyjee - You can find more information [here](https://github.com/datacamp/tutorial) and [here](https://github.com/datacamp/datacamp-light). 

Since you have written the tutorial in a Jupyter Notebook, I'd recommend you to 
- start an RMarkdown file with just the exercises (and their solutions). Make sure to set ```self_contained: false```!
- knit the document to an HTML one 
- Generate a Markdown file from your Jupyter Notebook
- Open the HTML file to copy the relevant HTML into the Markdown file that you have just generated. 

The problem with Jupyter Notebooks is that it doesn't seem to recognize the HTML nor the exercises when you actually make them in there - At least, I had that problem so I have always used the above workaround.
